# Generated by Django 5.1.6 on 2025-03-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_user_profile_picture_alter_user_activation_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_token',
            field=models.CharField(blank=True, default='etc9MSKbOmtKr5BFhxRWAswNFBko28dG', max_length=100, null=True),
        ),
    ]
