# Generated by Django 5.1.6 on 2025-03-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_alter_user_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_token',
            field=models.CharField(blank=True, default='becRoITwKYNI0NR0fzbBrHE19sPqWPXt', max_length=100, null=True),
        ),
    ]
