# Generated by Django 5.1.6 on 2025-03-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_alter_user_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_token',
            field=models.CharField(blank=True, default='mcu9861N24IDL4m1RRkwyWtTHHpftwoD', max_length=100, null=True),
        ),
    ]
